#define GEARUP _BV(4)
#define GEARDOWN _BV(7)

#define LED7 _BV(7)
#define LED6 _BV(6)
#define LED5 _BV(5)
#define LED4 _BV(4)
#define LED3 _BV(3)
#define LED2 _BV(2)
#define LED1 _BV(1)
#define LED0 _BV(0)
